### ISSUE TITLE
Could not reach your server when sharing from other apps

### ISSUE THREAD

**Issue by daniele2209** [LeoKlaus/Paperparrot#164]
**Describe the bug**
When I want to share a document from another app (e.g. from Rewe app or Barmenia App) I always get the error message "Could not reach your server, please check your connection"

**To Reproduce**
1. Go to 'Barmenia App'
2. Click on 'view document and then press the Share button'
3. Scroll down to 'paperparot app'
4. Click on "Document hinzufügen"
5. See error

**Expected behavior**
The shared document should be inside Paperparot and ready for upload. 

**Screenshots**

**Environment(please complete the following information):**
 - Device: [iPhone 15]
 - OS: [e.g. iOS17]
 - Version
 - Server Version (if applicable) [e.g. Paperless-ngx 2.01]
- latest paperparot version

**Additional context**

**Comment by LeoKlaus** [comment]
Hi Daniele,
thanks for reaching out!
This is probably related to a known bug.
An update with a bugfix for this should release soon, I've just got some small things to take care of before releasing it.

Are you connected to a Paperless-ngx Server or are you using Paperparrot standalone?

If you have any other Feedback or suggestions, feel free to let me know!

**Comment by daniele2209** [comment]
Hi Leo. 
I am using it with a paperless server (latest version)
Thanks for taking care and your support. 
Great piece of software. I love it.

**Comment by LeoKlaus** [comment]
Are you connecting locally? If so, using the IP of the server instead of the hostname should "fix" the issue until the update releases.

**Comment by daniele2209** [comment]
Hi. 
I am connecting locally. 
I just tried the workaround. 
Now I get the message "OK". 
But unfortunately no document appears in Paperparot. 

Daniel

**Comment by LeoKlaus** [comment]
Anything in your server logs?

**Comment by MaximilianHerrmann** [comment]
I had a similar issue --> not able to connect to server after trying to share an pdf from another app.

**1. Using the IP instead of a hostname fixed the issue.**
2. After selecting paperparrot as the app the document has to be shared with, the following screen just asks for the Titel of the file, no other import options possible.
3. Import works but only with the automated import rules, i.e. my document gets the tag INBOX, if correspondent or document rules apply, those are set.
5. I can find the document on my phone and on my server (ngx 1.9.2 (will do an update soon)

@daniele2209 : maybe you have too many files shown in your inbox or your filters are set wrong?

Hope this helps,
Max
