### ISSUE TITLE
[BUG] iPadOS App closes when clicking Settings

### ISSUE THREAD

**Issue by psychos4** [LeoKlaus/Paperparrot#182]
**Describe the bug**
App closes if you click Settings (Einstellungen) 

**To Reproduce**
1. Open App
2. Click on 'Einstellungen' (Settings) on the right bottom
3. App crashes / closes

**Environment:**
 - App Version: 2.1.3
 - Device: iPad (6th gen)
 - OS: iPadOS 
 - Version 16.3.1

On iPhone it works perfect.

**Comment by LeoKlaus** [comment]
Hey psychos4,
thanks for reaching out! This is definitely a bug.

Do you use Paperparrot with a Paperless server or just by itself?

I think I already know what causes this, I'll let you know once I have an update ready!

**Comment by psychos4** [comment]
I use a paperless-ngx server, but without Settings I can’t configure any server.
This error is only on the iPad on my iphone it works great. 

Thx

**Comment by LeoKlaus** [comment]
> I use a paperless-ngx server, but without Settings I can’t configure any server. This error is only on the iPad on my iphone it works great. Thx

In this case, it should suffice to reinstall the app on your iPad. When setting up Paperparrot, tap on "Connect to a Paperless-ngx-Server" instead of "Start using the app". As you're using the german translation, it's "Verbindung zu einem Paperless-ng(x)-Server herstellen":
![image](https://github.com/LeoKlaus/Paperparrot/assets/66492595/ecc20652-5d14-4cbb-aa7f-8f0bb1881458)

I'll still leave this open until I have fixed the issue.

**Comment by psychos4** [comment]
thx, so it works. ✅
