### ISSUE TITLE
When scanning, uploading a document make title text pre-seelcted

### ISSUE THREAD

**Issue by Piste** [LeoKlaus/Paperparrot#95]
**Is your feature request related to a problem? Please describe.**
When I scan and upload, if I want to enter a title, I first have to delete the existing title placeholder text.

**Describe the solution you'd like**
Two solutions:
- make the title box empty so I don't have to delete anything
- or pre-select the text in the title box so the first time I type, it overwrites it

**Comment by LeoKlaus** [comment]
I've added a clear button to the text field and set the default value to be the name of the file instead of "Untitled Document". Pre-selecting the text lead to an unintuitive ux, I hope this still solves your problem.

This will ship with the upcoming 1.3 update which is already in TestFlight and should become publicly available in the next week.

**Comment by Piste** [comment]
Sweet. Looking forward to the update. I'm happy to participate in the TestFlight versions too.

**Comment by LeoKlaus** [comment]
Sure, if you could message me on Discord derkleineleo#6682 or send me a mail at support@paperparrot.me I'll send you an invite.
